version: '2.19.1'

services:
  db:
    image: mysql:5.7.42
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3308:3306
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
